# Sources
DIR_SOURCES := aural.c background.c border_outline.c display_sizing.c \
	effects_stacking.c font.c generated_list.c margin.c padding.c \
	page.c positioning.c properties.c table.c text.c ui.c utils.c

include build/makefiles/Makefile.subdir
